<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit21e7c608f8f183f08e6d87d77b1821bf
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PWall\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PWall\\' => 
        array (
            0 => __DIR__ . '/..' . '/lib',
        ),
    );

    public static $classMap = array (
        'PWall\\Client' => __DIR__ . '/..' . '/lib/Client.php',
        'PWall\\Exception\\ExceptionInterface' => __DIR__ . '/..' . '/lib/Exception/ExceptionInterface.php',
        'PWall\\Exception\\InvalidArgumentException' => __DIR__ . '/..' . '/lib/Exception/InvalidArgumentException.php',
        'PWall\\Helper\\Constants' => __DIR__ . '/..' . '/lib/Helper/Constants.php',
        'PWall\\Helper\\ProxyHelper' => __DIR__ . '/..' . '/lib/Helper/ProxyHelper.php',
        'PWall\\Request' => __DIR__ . '/..' . '/lib/Request.php',
        'PWall\\Response' => __DIR__ . '/..' . '/lib/Response.php',
        'PWall\\SaleResponse' => __DIR__ . '/..' . '/lib/SaleResponse.php',
        'PWall\\Utils\\Logger' => __DIR__ . '/..' . '/lib/Utils/Logger.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit21e7c608f8f183f08e6d87d77b1821bf::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit21e7c608f8f183f08e6d87d77b1821bf::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit21e7c608f8f183f08e6d87d77b1821bf::$classMap;

        }, null, ClassLoader::class);
    }
}
