<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'PWall\\Client' => $vendorDir . '/lib/Client.php',
    'PWall\\Exception\\ExceptionInterface' => $vendorDir . '/lib/Exception/ExceptionInterface.php',
    'PWall\\Exception\\InvalidArgumentException' => $vendorDir . '/lib/Exception/InvalidArgumentException.php',
    'PWall\\Helper\\Constants' => $vendorDir . '/lib/Helper/Constants.php',
    'PWall\\Helper\\ProxyHelper' => $vendorDir . '/lib/Helper/ProxyHelper.php',
    'PWall\\Request' => $vendorDir . '/lib/Request.php',
    'PWall\\Response' => $vendorDir . '/lib/Response.php',
    'PWall\\SaleResponse' => $vendorDir . '/lib/SaleResponse.php',
    'PWall\\Utils\\Logger' => $vendorDir . '/lib/Utils/Logger.php',
);
